### ISSUE TITLE
set_bytes returning status failure

### ISSUE THREAD

**Issue by oninross** [Sightengine/client-nodejs#2]
`sightengine.check(['nudity', 'wad']).set_bytes(binary).then(function (result) {
    // read the output (result)
    console.log(result)
}).catch(function (err) {
    // handle the error
    console.log(err)
});`

Im trying this code and passing binary data through it.  But its returning a code 51 error and "Please specify models".  Can I assume that binary data is base64?

**Comment by ghost** [comment]
Hello,
You can use fs.createReadStream to retrieve the binary data.

Example of code:

```javascript
var fs = require('fs');
var path = require('path');

var binary = fs.createReadStream(path.resolve(__dirname, 'assets', 'image.jpg'));

sightengine.check(['nudity', 'wad']).set_bytes(binary).then(function (result) {
  console.log(result)
}).catch(function (err) {
  console.log(err)
});
```

Let me know if it works :)

**Comment by oninross** [comment]
The image is taken from a camera. It hasn't been saved yet.  But i do have it in base 64. Will that work?

**Comment by ghost** [comment]
No, if you want the binary data you have to interpret (decode) it.

I think you can use a buffer or you can use this module to retrieve a stream from an image in base 64:
https://www.npmjs.com/package/base64-stream

**Comment by oninross** [comment]
Silly question:  how? documentation or google is not much help.  I just cant connect the dots from base64 to binary stream

**Comment by ghost** [comment]
Maybe this link could help you?

https://stackoverflow.com/questions/8110294/nodejs-base64-image-encoding-decoding-not-quite-working
